# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12edd756f50f3181adb96157e92a1ccc16d20accbe6e9876f514c95c18d769ae381eb4809a913d3e88f50939dc6af083b367c9a658bf0671dabab0685de34b2
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 315634388791652
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
  secret_key_base: b8f14bc14127e00b34210aba0cb8d38a62c3ecf867cb17844683a9dc92a421dfa771f580bf6dd9cd872d7bf19a76a9fd4ed014528a77a8911c3a697b98473a9f
  facebook_app_id: 315634388791652
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 315634388791652
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
